### ISSUE TITLE
Can I use machine learning libraries(frameworks) in my project ?

### ISSUE THREAD

**Issue by bigship** [bigship/CAS741#1]
@smiths Hi Prof, 
This is Colin Chen, your student from CAS 741 course.
 
First, I cound't find other students' issues on [GitLab](https://gitlab.cas.mcmaster.ca/smiths/cas741/issues?scope=all&utf8=%E2%9C%93&state=opened),  so I think GitHub is the place we do our issue practise right ?

Anyway, my supervisor Dr. Rong Zheng's research interests include machine learning, mobile computing and networked systems, and I myself also have strong interest on mobile app design. So I think a mobile app about machine learning would be perfect for the class project. 

As you may probably aware that, Apple has some great machine learning [frameworks](https://developer.apple.com/machine-learning/) out there, I think this opens up all kinds of possibilities on the mobile phone. These frameworks are designed to be easily used, and no  prior background is needed which is great for me (I'm just start learning the theory). So I can get most out of it by learning enough to make machine learning (scientific computing ) a useful tool.

Currently, I got some ideas about using machine learning techniques to solve problems using images, like image classification, object detection with bounding boxes and object segmentation etc.  I will deliver a standard problem statement about the project on GitHub as well. 

Regards

**Comment by smiths** [comment]
Yes @bigship, you can proceed with a problem statement based on a machine learning app.  Please clarify in your problem statement the application that you will be applying machine learning to.

Yes, as discussed in class, you create  your issues in the Drasil repo on GitHub at:
https://github.com/JacquesCarette/Drasil/issues

The issues are based on your review of any of the SRS documents for the sample projects at:
https://jacquescarette.github.io/Drasil/
