### ISSUE TITLE
Problem statement review

### ISSUE THREAD

**Issue by bigship** [bigship/CAS741#2]
@smiths 
Hi, Professor
Please review my [ProblemStatement](https://github.com/bigship/CAS741/blob/master/docs/ProblemStatement/ProblemStatement.pdf) and give me some advices, thanks.

**Comment by smiths** [comment]
@bigship, I approve your project based on the problem statement.  With your future writing, please do another editing pass on grammar and punctuation.  The writing checklist in the docs folder in our CAS repo should be helpful in guiding you for your final review.
In writing  your SRS, please be sure to include the theory of machine learning.  We don't want your project to become all about the iOS development.  We want to keep the scientific computing content high.  :smile:

**Comment by bigship** [comment]
@smiths Of course, I will spend most of the time on the machine learning theory part, it is a good practise on image classification.

**Comment by smiths** [comment]
@bigship,  you can close this issue now.  I would close it, but I do not have permission to close issues.

**Comment by smiths** [comment]
I now have access, so I can close this issue.
