### ISSUE TITLE
Please add me as contributor on your project

### ISSUE THREAD

**Issue by smiths** [bigship/CAS741#3]
@bigship, please add me to your project.  In some cases my feedback to you will be via pushes to your repo.  I also would like to be able to close issues.

**Comment by bigship** [comment]
@smiths Already added. I'll close this issue.

**Comment by smiths** [comment]
I'm sorry @bigship, but I do not have push access for your repo.  I also do not have the ability to close issues.  I'm not sure what setting is set incorrectly, but it will be frustrating if I need to do a pull request to comment on your code.  I would reopen this issue, but I do not have permission.

**Comment by smiths** [comment]
Never mind.  The problem is fixed now.  I hadn't yet clicked on the accept invitation.  (I thought I already had.)  :smile:

**Comment by smiths** [comment]
@bigship, I pushed a small fix to your problem statement as I was working out my access problems.  You should do a git pull before editing.
